Squashed 'site-lisp/haskell-mode/' changes from 6a4d4bd..47d90c8
47d90c8 Support multiple presentations at once in the same REPL
d027f9f Thread hash through presentation functions
a0dd740 Split interaction mode into two minor modes a la indentation
591d1a8 Fix inserting of type in haskell-describe
5c817ee Add initial haskell-describe function
e300782 Add import suggestions based on haskell-docs
050a119 Support 7.8 in extension completion
faf4c56 Support GHC 7.8's message format for extension suggestions
d62f51a Improve usefulness of file-relative-name in cycle code
36e39a4 Pick up import cycles as loading errors with fake line numbers
073344e Merge pull request #282 from bergey/cabal-path
52fafce Merge pull request #284 from ryantm/byte-compile-warnings
a73cb69 add missing requires in haskell-debug
905faf5 Merge pull request #283 from ryantm/byte-compile-warnings
ae0e87c Add try-type
95dbb75 do not require w3m
5ffbf1d stop using goto-line as recommended by emacs help on goto-line
8f02b8c Use haskell-process-path-cabal everywhere
ca84191 Make popups disableable (fixes #280)
f7f1a17 Show ... if more results in module completion, a la ido-mode
5985f84 Use `haskell-complete-module' for module completions
e49c0e5 Satisfy Makefile warnings for haskell-complete-module
c285ee3 Fix e reference in haskell-process.el
55b9c7c Add haskell-complete-module
a8c4c12 Don't ask about importing the same module more than once
d3f3f5b Handle errors and quitting in process commands more gracefully
89917d2 Skip whole module qualification in hoogle import suggestions
76c505d Add kill-whole-line support in REPL (closes #277)
2df11b6 Fix warning detection regex (fixes #275)
cda2fc8 Merge pull request #274 from Philonous/master
69ead72 Fix getLine with no stdout output
9f65077 curb process restart spam
c2206c9 Remove debug message
976917b Add back padding option in haskell-align-imports (#183)
3d834d4 Fix OverloadedStrings suggester
cc161d7 Test cases for haskell-sort-imports (#270)
fbdc679 Sort on just module names (#270)
8f2a7e0 Rewrite sort-imports to not be line-based (#270)
efe9bbe Make sure to expand filename when getting definition dir
c58058e Trivial function for dumping minimal imports
832fcc6 Fix haskell-process-hoogle-ident
02fedeb Experimental refactor of jumping to definition
ed148c9 Fix make build for Emacs 23
b180578 Throw error if trying to create a session that already exists
ff2f361 Improve session switching
c8a72bd Avoid prompting on incomplete sessions when sifting
52b93a6 Fix face references in haskell-debug (fixes #268)
ee537a5 Fix Show detection in presence of newline
5df78d2 Fix ill-advised removal of prompt stripping
1eb2b2b Let haskell-process-hoogle-ident fail silently on error
116e66a Add hoogle server commands
88b4091 Modify hoogle-suggest regexes for ghc 7.8 compatibility
23b385b Additional fix for ghci prompt inferior-haskell-mode
8fbc5f6 Support stdin input in the REPL
e827a17 Remove redundant newline in colorized output
7fb632a Update README to ref wiki manual
cefa9e9 Make showing types of ambiguous/no-show expressions customizable
7102355 Show types for ambiguous type variables in the REPL, too
a22f7a1 Make import questioning more persistent at getting an answer
33f0011 Add module template auto-insertion function
8a774c7 Support arbitrary cabal command
e9934ab Fix auto-type-showing in presence of :set +t
e1a0d86 Show the type of something if no Show instance is available
c4dc84f Add require cl
c6d22db Fix format of customization of -w3m-haddock-dirs
fa0835f Handle unrepresentable things in :present
9073057 Update to present-1.0 (you need to cabal install present==1.0)
007f585 Fix to pass make check
7c1d6b1 Fix missing function reference
254ba72 Handle compile messages from GHC that contain [TH]
9324171 Much better list presentations
18713e6 Indent alg-types with newlines and regular indentation
5f90c1d Support multiple directories in w3m-haddock
eddb5c1 Add preliminary :present support
f6c4b86 Fix error in haskell-interactive-mode completion (#263)
5e4907f Fix spacing in type info regression (#264)
aa07205 Popup error buffer instead of displaying them in the REPL
35527f9 Add sexp-based collapsing support in REPL
099c82c Strip newlines from haskell-process-do-type
5128d4d Fix haskell-debug for recent prompt handling changes.
433c16a Dump complete output if zero compiler messages from cabal
b5ca602 Strip out extraneous prompts
58810a1 Declare use of -insert-garbage
c2e7dbf Echo extraneous output after prompt has been received
277e8e8 Use end-of-transmission for prompt
d9aa484 Only save again after stylish if necessary.
3d1ff09 Print a newline as soon as the command starts to execute.
a0a33d3 Make haskell-align-imports-padding a total function
110aa35 Add a command to send cabal macros (#255)
e9587d9 Make haskell-interactive-at-prompt return position
f1962fe Add back 'break properties to breakpoint list
c621a21 Support next/previous properly
0963af4 Reset history and bindings cache after abandoning
f0748c2 Re-step after reloading
af495c2 Debugger with bindings display
d2ba091 Keep hold of the back trace for helpful display at the end
6219ad6 Good progress on debugger stepping
d5b3577 fixes #250, haskell-interactive mode broken under certain conditions
92581b1 A bit more of the debugger mode
69fe380 Start of implementation of interactive debugger
aec3d05 Add .dump-simpl files to ghc-core auto-mode-alist
6bb7cad More liberal source match
92f2f26 Add customization setting for header color
6bd7c56 Add haskell-w3m-open-haddock
c1f982e Remove accidentally left in font-lock experiment
9b43204 Add multi-line support in REPL
5a3a996 Add haskell-process-reload-devel-main interactive command
2684a4f Use marker instead of regexps in haskell-interactive-mode prompt
5ce988e Support continuations in the process loading
6bec474 Add w3m-haddock.el
7ddc44f Disable hoogle suggestion by default
6ca09d0 Replace completing-read-function with custom for haskell-mode
1248ab0 Defvar completing-read-function
4bcb2db Declare 'delete-active-region' in haskell-indentation
ec00623 Replace 'ido-completing-read' with 'completing-read-function'
1af6521 Another attempt at removing EOF newline.
2a97e4c Remove EOF newline. These are explicit in snippets.
6615415 Ability to configure the import line on suggestions
17c8a28 Fix dynamic-binding reference
96ffb1f Separate running a line in haskell-interactive-mode into another function
1db9dde Use && instead of ; because this works on Windows, too (refs #232)
1834c3b Option to automatically chmod .ghci files that GHCi ignores
55408fc Make showing debugging tips an option
692afb9 Make errors expanded by default
7b3946d Check for build/install as substring
a4a8a09 Allow whitespace before settings.
182e34f Don't use replace-regexp to appease make check
1c6ef10 Support god-mode on SPC key
175c6cc Better "not in scope" detection
ab7ee92 Strip out M./S./L. typical module prefixes for suggestion functionality
38e8c06 Make navigate-imports a bit more useful in absense of import list
c85219a Ignore package results
5ae3835 Support the case of multiple available modules for auto-import
89b036d Automatically add package to cabal file
f44c2d3 Make dummy global binding to avoid not-in-scope warnings
ed4d9e8 Automatically add import lines via Hoogle
9292ba1 Fix undefined reference to shm-display-quarantine in haskell-present
fa1b365 Support jumping to filenames inside strings
7e74535 Small indentation fix
0ae55ff Quick hack to remove "Compilation failed" line
f13eae5 Support commenting out of imports
dc3a02f Add a function to guess the module name of the current buffer
c910ed0 Don't show shm's display quarantines in presentation mode
3f7747e Fix delete-backward-char in haskell-indentation (fixes #211)
3ade6a8 Merge pull request #214 from brandonw/master
29c0b98 Merge pull request #217 from adimit/patch-1
c9424aa add support for cabal repl build targets
7ae7411 Add haskell-bot.el, for interacting with locally installed lambdabot
54e6ccd Fix import.qualified.
4f87331 Fix internal GHC module translation
c925867 Revert "Fix internal GHC module translation"
43f2747 Always use the ident as an anchor
0ff0841 Update internal GHC module translations
53a63a1 Fix internal GHC module translation

git-subtree-dir: site-lisp/haskell-mode
git-subtree-split: 47d90c83f101596be92a44d98b9ebf8a6089efc0